---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-api
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/genokan/practice-lab.git
        revision: main
        files:
          - path: gitops/releases/hello-api-*.yaml
  template:
    metadata:
      name: '{{ .name }}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: '{{ .chart.repository }}'
          targetRevision: '{{ .chart.digest }}'
          path: .
          helm:
            releaseName: '{{ .releaseName }}'
            valueFiles:
              - '$values/{{ .valuesFile }}'
        - repoURL: https://github.com/genokan/practice-lab.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
