environment: staging
replicaCount: 2
lab:
  enabled: true
  maxDurationSeconds: 300
  maxLatencyMilliseconds: 5000
image:
  repository: ghcr.io/genokan/practice-hello-api
  tag: ""
  digest: sha256:70f6f344f3314b091d8123c98723f8201f03642a63b4e4f0ec7d6a6e326baae4
  pullPolicy: IfNotPresent
service:
  targetPort: 4000
ingress:
  enabled: true
  host: hello-staging.opsguy.io
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 256Mi
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "4000"
