environment: staging
replicaCount: 2
lab:
  enabled: true
  maxDurationSeconds: 300
  maxLatencyMilliseconds: 5000
  maxCpuWorkers: 8
  maxMemoryMiB: 512
load:
  enabled: true
  ui:
    enabled: true
  targetUrl: http://hello-api-staging-hello-api
image:
  repository: ghcr.io/genokan/practice-hello-api
  tag: ""
  digest: sha256:185074c275b2205947ec66b95f5c92a22367c19e0328e5e78ecd06e7724d4c71
  pullPolicy: IfNotPresent
service:
  targetPort: 4000
ingress:
  enabled: true
  host: hello-staging.opsguy.io
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
podDisruptionBudget:
  enabled: true
  minAvailable: 1
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "4000"
