---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-pki-edge
  namespace: argocd
spec:
  vault:
    server: https://vault.opsguy.io
    path: practice-lab-pki/sign/argocd-edge
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes-practice-lab
        role: cert-manager-argocd-edge
        serviceAccountRef:
          name: vault-pki-edge-issuer
          audiences:
            - vault://argocd/vault-pki-edge
            - https://kubernetes.default.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-pki-server
  namespace: argocd
spec:
  vault:
    server: https://vault.opsguy.io
    path: practice-lab-pki/sign/argocd-server
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes-practice-lab
        role: cert-manager-argocd-server
        serviceAccountRef:
          name: vault-pki-server-issuer
          audiences:
            - vault://argocd/vault-pki-server
            - https://kubernetes.default.svc.cluster.local
