---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-production
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/genokan/practice-lab.git
      targetRevision: main
      path: charts/hello
      helm:
        releaseName: hello-production
        valueFiles:
          - $values/environments/production/values.yaml
    - repoURL: https://github.com/genokan/practice-lab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
